- .gitignore
- RA18_RobotCode.iml
Because I'm old and cranky and like my editor.
> Add IDEA import files for IDEA users

- src/org/redalert1741/powerup/Robot.java
Adds code and note for determining the alliance colors via the FMS.
> Add example code for panel assignment

- .travis.yml
Made it do the thing... \o/
Closes #13
> Make Travis build on commits to master

- SETUP-ECLIPSE.md
> Add eclipse instructions

- .github/PULL_REQUEST_TEMPLATE.md
The irony of not having a template, because your PR _adds_ the template.  😂
Closes #23
> Added some templates

- src/main/java/org/redalert1741/robotBase/config/Config.java
- src/test/java/org/redalert1741/robotbase/config/ConfigTest.java
- src/test/resources/org/redalert1741/robotbase/config/test_config.txt
There was no testing around the config module.
Add some testing! \o/
Run the tests? 😁
> Add config testing

- src/test/java/org/redalert1741/robotbase/input/InputTest.java
There was no testing around the input module.
Add some testing!  \o/
Run the tests?  😁
> Add input testing

- src/main/java/org/redalert1741/powerup/Robot.java
- src/main/java/org/redalert1741/robotBase/auto/core/AutoFactory.java
- src/main/java/org/redalert1741/robotBase/auto/core/AutoMove.java
- src/main/java/org/redalert1741/robotBase/auto/core/AutoMoveEnd.java
- src/main/java/org/redalert1741/robotBase/auto/core/AutoMoveEndFactory.java
- src/main/java/org/redalert1741/robotBase/auto/core/AutoMoveMove.java
- src/main/java/org/redalert1741/robotBase/auto/core/AutoMoveMoveFactory.java
- src/main/java/org/redalert1741/robotBase/auto/core/Autonomous.java
- src/main/java/org/redalert1741/robotBase/auto/core/JsonAutoFactory.java
- src/main/java/org/redalert1741/robotBase/auto/end/EmptyEnd.java
- src/main/java/org/redalert1741/robotBase/auto/end/TimedEnd.java
- src/main/java/org/redalert1741/robotBase/auto/move/EmptyMove.java
- src/main/java/org/redalert1741/robotBase/config/Config.java
- src/main/java/org/redalert1741/robotBase/config/Configurable.java
- src/main/java/org/redalert1741/robotBase/input/EdgeDetect.java
- src/main/java/org/redalert1741/robotBase/logging/DataLogger.java
- src/main/java/org/redalert1741/robotBase/logging/Loggable.java
There were mixed tabs and spaces.
Remove all of the tabs.
None?
> Removed all the tabs... 😱

- src/main/java/org/redalert1741/powerup/TankDrive.java
There's no tank drive class
Add a tank drive class
probably not
> Add TankDrive.java

- src/main/java/org/redalert1741/robotBase/logging/DataLogger.java
NetworkTables deprecated a bunch of the api, #9 
Make NetworkTables do the things its supposed to again
This changed like 4 lines of code
> fix network tables

- src/test/java/org/redalert1741/robotbase/auto/AutoTest.java
- src/test/resources/org/redalert1741/robotbase/auto/async-test.json
there wasn't another auto test
add another auto test
> add another auto test

- src/main/java/org/redalert1741/robotBase/auto/core/JsonAutoFactory.java
there was a lame print
remove the lame print
it was one line that got removed
> remove lame print

- src/main/java/org/redalert1741/robotbase/config/Config.java
- src/test/java/org/redalert1741/robotbase/config/ConfigTest.java
The config repeated so much
slightly less repeat maybe besides more classes
still wip
> Make config better

- src/main/java/org/redalert1741/robotbase/auto/end/EmptyEnd.java
- src/main/java/org/redalert1741/robotbase/auto/end/TimedEnd.java
- src/main/java/org/redalert1741/robotbase/auto/move/EmptyMove.java
codeclimate doesn't like empty functions
put comments in i guess
no code is being added (hopefully)
> Cleanup in auto

- src/main/java/org/redalert1741/robotbase/config/Config.java
config is still complex
extract line parse
> More config

- src/main/java/org/redalert1741/powerup/Scoring.java
Scoring has sparks that need to be removed.
Remove sparks. Add DoubleSolenoid.
Received beating from codeclimate
> Modify scoring

- src/main/java/org/redalert1741/powerup/Manipulation.java
Constructor for manipulation was not created.
Created manipulation constructor.
Copy-pastad from Scoring constructor with minor changes
> Add manipulation

- .travis.yml
- build.gradle
- src/test/java/org/redalert1741/powerup/JunitTest.java
- src/test/java/org/redalert1741/robotbase/auto/AutoTest.java
- src/test/java/org/redalert1741/robotbase/config/ConfigTest.java
- src/test/java/org/redalert1741/robotbase/input/InputTest.java
Turns out, we're not _actually_ reporting code coverage.
Add cobertura to do such things.
Check to see if Code Climate is reporting code coverage.
> Added Cobertura config

- build.gradle
- logging.properties
- src/main/java/org/redalert1741/powerup/Robot.java
There *was* logging, but it was turrible.
I added arewsome loggin
Testing is for suckers
> Add custom logging to the robot

- .travis.yml
Grrrrrr.... 
This is a continuation of #45.
> This time? (code coverage _still_ isn't reporting correctly)

- .codeclimate.yml
code complexity of 5 is a bit much
make it 10 (theoretically)
i hope this doesn't have to be tested
> add .codeclimate.yml

- src/main/java/org/redalert1741/powerup/TankDrive.java
Tank Drive needs logging.
Add logging to tank drive.
We might wanna do that.
> add logging to TankDrive

- src/main/java/org/redalert1741/robotbase/auto/core/AutoMove.java
- src/main/java/org/redalert1741/robotbase/auto/core/Autonomous.java
- src/test/java/org/redalert1741/robotbase/auto/AutoTest.java
Auto wouldn't restart when start is called a second time
`finished = false;`
> Auto restarts properly

- src/main/java/org/redalert1741/robotbase/config/Config.java
- src/main/java/org/redalert1741/robotbase/config/Configurable.java
- src/test/java/org/redalert1741/robotbase/config/ConfigTest.java
- src/test/resources/org/redalert1741/robotbase/config/test_config.txt
small problem in configurable, also finish testing
fix that
had to run dos2unix on test_config.json
> Configurable + Config Testing

- .gitignore
> ignore doc

- src/main/java/org/redalert1741/robotbase/auto/core/AutoMove.java
- src/main/java/org/redalert1741/robotbase/auto/core/AutoMoveEnd.java
- src/main/java/org/redalert1741/robotbase/auto/core/AutoMoveMove.java
- src/main/java/org/redalert1741/robotbase/auto/core/AutoPojo.java
- src/main/java/org/redalert1741/robotbase/auto/core/Autonomous.java
- src/main/java/org/redalert1741/robotbase/config/Config.java
- src/main/java/org/redalert1741/robotbase/config/Configurable.java
- src/main/java/org/redalert1741/robotbase/input/EdgeDetect.java
- src/main/java/org/redalert1741/robotbase/logging/DataLogger.java
- src/main/java/org/redalert1741/robotbase/logging/Loggable.java
not enough javadoc
add moar javadoc
only code changed was some internal Autonomous functions went from `public` to `private`
> Moar javadoc

- src/main/java/org/redalert1741/powerup/Manipulation.java
Manipulation has a brake, but there is no code for the brake.
Code for the brake was created.
Used TankDrive as a reference for brake code.
> add solenoid for brake

- src/main/java/org/redalert1741/powerup/TankDrive.java
The Drive Train wasn't simple enough. #73 
Slave the back motors to the front motors
> Slave back motors to front motors

- src/main/java/org/redalert1741/powerup/Manipulation.java
Manipulation has a spark.
Remove spark from manipulation.
Used TankDrive as a reference.
> Change manipulation

- src/main/java/org/redalert1741/powerup/Manipulation.java
- src/main/java/org/redalert1741/powerup/TankDrive.java
- src/main/java/org/redalert1741/robotbase/wrapper/RealTalonSrxWrapper.java
- src/main/java/org/redalert1741/robotbase/wrapper/TalonSrxWrapper.java
- src/test/java/org/redalert1741/robotbase/wrapper/FakeTalonSrxWrapper.java
you couldn't pid with the wrapper
fix that
had to change talonsrxwrapper to an abstract class instead of interface
> wowzo more pid for TalonSrxWrapper

- src/main/java/org/redalert1741/powerup/Manipulation.java
- src/main/java/org/redalert1741/powerup/TankDrive.java
- src/main/java/org/redalert1741/robotbase/wrapper/RealTalonSrxWrapper.java
- src/main/java/org/redalert1741/robotbase/wrapper/TalonSrxWrapper.java
- src/test/java/org/redalert1741/powerup/ManipulationTest.java
- src/test/java/org/redalert1741/powerup/TankDriveTest.java
- src/test/java/org/redalert1741/robotbase/wrapper/FakeTalonSrxWrapper.java
- src/test/resources/org/redalert1741/powerup/manipulationconfig.txt
- src/test/resources/org/redalert1741/powerup/tankdriveconfig.txt
> Improve talon wrapper

- src/main/java/org/redalert1741/powerup/Manipulation.java
- src/main/java/org/redalert1741/powerup/Scoring.java
- src/main/java/org/redalert1741/robotbase/wrapper/DoubleSolenoidWrapper.java
- src/main/java/org/redalert1741/robotbase/wrapper/RealDoubleSolenoidWrapper.java
- src/test/java/org/redalert1741/robotbase/wrapper/FakeDoubleSolenoidWrapper.java
doublesolenoid doesn't log
do that
> wow doublesolenoid logging

- src/main/java/org/redalert1741/powerup/Manipulation.java
- src/main/java/org/redalert1741/powerup/TankDrive.java
- src/main/java/org/redalert1741/robotbase/wrapper/RealSolenoidWrapper.java
- src/main/java/org/redalert1741/robotbase/wrapper/SolenoidWrapper.java
- src/test/java/org/redalert1741/powerup/TankDriveTest.java
- src/test/java/org/redalert1741/robotbase/wrapper/FakeSolenoidWrapper.java
solenoid didn't log itself
now it does
> More solenoidwrapper

- src/main/java/org/redalert1741/robotbase/auto/README.md
> Explain automoves

- build.gradle
gradlerio did an update
do that
> bump gradlerio version

- src/main/java/org/redalert1741/robotbase/auto/core/AutoFactory.java
- src/main/java/org/redalert1741/robotbase/auto/core/AutoMove.java
- src/test/java/org/redalert1741/robotbase/auto/AutoTest.java
- src/test/resources/org/redalert1741/robotbase/auto/missing-args-test.json
thats a lot of garbage to do nothing
default to `EmptyMove` and `EmptyEnd`
should have all the test coverage
> add default moves (mk 2)

- auto/left_scale.json
- auto/left_switch.json
- auto/middle_left.json
- auto/middle_right.json
- auto/min-auto.json
- auto/right_scale.json
- auto/right_switch.json
- src/main/java/org/redalert1741/powerup/Climber.java
- src/main/java/org/redalert1741/powerup/Manipulation.java
- src/main/java/org/redalert1741/powerup/Robot.java
- src/main/java/org/redalert1741/powerup/TankDrive.java
- src/main/java/org/redalert1741/powerup/auto/end/TalonDistanceEnd.java
- src/main/java/org/redalert1741/powerup/auto/move/ManipulationLiftMove.java
- src/main/java/org/redalert1741/powerup/auto/move/TankDriveRampRateMove.java
- src/main/java/org/redalert1741/powerup/auto/move/TankDriveTankMove.java
- src/main/java/org/redalert1741/robotbase/auto/core/AutoFactory.java
- src/main/java/org/redalert1741/robotbase/auto/core/AutoMove.java
- src/main/java/org/redalert1741/robotbase/wrapper/RealTalonSrxWrapper.java
- src/main/java/org/redalert1741/robotbase/wrapper/TalonSrxWrapper.java
- src/test/java/org/redalert1741/powerup/ManipulationTest.java
- src/test/java/org/redalert1741/powerup/auto/end/TalonDistanceEndTest.java
- src/test/java/org/redalert1741/powerup/auto/move/ManipulationMoveTest.java
- src/test/java/org/redalert1741/robotbase/auto/AutoTest.java
- src/test/java/org/redalert1741/robotbase/wrapper/FakeTalonSrxWrapper.java
- src/test/resources/org/redalert1741/robotbase/auto/missing-args-test.json
we need more code before competition(mostly lift and auto)
gradually add everything overtime till competition
good luck
> Pre comp 1

- src/main/java/org/redalert1741/powerup/Manipulation.java
Didn't have a second follower
added a second follower
> add secondFollower
